name: Semgrep CE

on:
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep:latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This is important to get all history for diff

      - name: Get changed files
        shell: bash
        run: |
          git config --global --add safe.directory "$(pwd)"
          git fetch origin ${{ github.base_ref }}
          echo "CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | tr '\n' ' ')" >> $GITHUB_ENV
      
      - name: Run Semgrep on changed files
        shell: bash
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            semgrep scan --config auto --json --output semgrep.json $CHANGED_FILES
            semgrep scan --config auto --sarif --output semgrep.sarif $CHANGED_FILES
          else
            echo "No files changed in this PR"
            echo "[]" > semgrep.json
            echo '{"runs": []}' > semgrep.sarif
          fi
      
      - name: Upload SARIF to github
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
